---
- name: Delete Apps at the Edge
  hosts: bastion
  become: yes
  
  tasks: 

    - name: Delete apps from ArgoCD
      shell: /usr/local/bin/argocd --insecure --grpc-web login {{ _argocd_url }}  --username {{ _argocd_default_user }} --password {{ _argocd_default_user_password }}; argocd app delete {{ item }}-edge-factory 
      args:
        chdir: "{{ var_user_homepath }}"
      loop: "{{ var_cluster_list }}"

    # - name: Check pacman deployment progress
    #   shell: /usr/local/bin/argocd --insecure --grpc-web login {{ _argocd_url }} --username {{ _argocd_default_user }} --password {{ _argocd_default_user_password }}; wait-for-argo-app cluster1-pacman; argocd app sync cluster1-pacman; wait-for-argo-app cluster2-pacman; argocd app sync cluster2-pacman; wait-for-argo-app cluster3-pacman; argocd app sync cluster3-pacman
    #   args:
    #     chdir: "{{ var_user_homepath }}"

    # - name: Validate the pacman namespaces
    #   shell: /usr/local/bin/argocd --insecure --grpc-web login {{ _argocd_url }} --username {{ _argocd_default_user }} --password {{ _argocd_default_user_password }}; for i in cluster1 cluster2 cluster3; do oc get namespace pacman --context $i; done
    #   args:
    #     chdir: "{{ var_user_homepath }}"

    # - name: Wait for the deployment to become ready
    #   shell: /usr/local/bin/argocd --insecure --grpc-web login {{ _argocd_url }} --username {{ _argocd_default_user }} --password {{ _argocd_default_user_password }}; for cluster in cluster1 cluster2 cluster3; do wait-for-deployment $cluster pacman pacman;done
    #   args:
    #     chdir: "{{ var_user_homepath }}"
